gegewepeh
rmt-07-glasgow-fox/fancy-todo pull request #20
Opened 2021-01-04 11:05 UTC by gegewepeh

Dokumentasi belum selesai, router dan controller untuk CRUD juga blum

2021-01-04 15:00 UTC, dmtrxw requested changes

2021-01-04 15:01 UTC, closed without merging

2021-01-04 15:05 UTC, gegewepeh commented on server/controllers/ToDoController.js
> +          res.status(201).json(data[1])
siap kak

2021-01-04 15:06 UTC, gegewepeh commented on server/controllers/ToDoController.js
> +        if (data[0] === 1) {
siap kak di rename smua yang kurang jelas

2021-01-04 15:06 UTC, gegewepeh commented on server/models/todo.js
> +          msg: 'Email required!'
maap kak pas ngerjain ada bengong2 bingung dikit, agak blunder

2021-01-04 15:06 UTC, gegewepeh commented on server/api_doc.md
> +  "status": "2020-03-20T07:15:12.149Z",
oops

2021-01-04 15:06 UTC, gegewepeh commented on server/api_doc.md
> +    "status": "<true or false>",
baik kak

2021-01-05 11:21 UTC, gegewepeh commented
authorization done