Mochammad Husni Rizal
rmt-07-glasgow-fox/fancy-todo pull request #26
Opened 2021-01-04 11:18 UTC by ical10

Server-side development:
- [x] GET todos
- [x] POST todos
- [x] GET todos by id
- [x] PUT todos by id
- [ ] PATCH todos by id
- [ ] DELETE todos by id

2021-01-04 12:32 UTC, ivantjendra commented on server/controllers/todosController.js
> +const {Todo} = require('../models')
ini di spasi sebelum dan sesudah Todo ya.
```js
const { Todo } = require('../models')
```

2021-01-04 12:33 UTC, ivantjendra commented on server/controllers/todosController.js
> +                res.status(500).json({message: "Internal server error."})
ini juga sama
```js
res.status(500).json({ message: "Internal server error." })
```

2021-01-04 12:33 UTC, ivantjendra commented on server/controllers/todosController.js
> +                res.status(500).json({message: "Internal server error."})
dan yang lain nya juga kalo ada object ya

2021-01-04 12:34 UTC, ivantjendra commented on server/controllers/todosController.js
> +                    if (error.type === 'Validation error') {
ini tembak name aja SequelizeValidationError

2021-01-04 12:35 UTC, ivantjendra commented on server/models/todo.js
> +    title: DataTypes.STRING,
ini masing - masing field di kasih validasi untuk notEmpty dan allowNull false nya

2021-01-04 12:35 UTC, ivantjendra commented on server/routes/index.js
> +router.get('/todos', todosController.getTodos)
ini kalo mau lebih rapi di pisah file sendiri si /todos nya. jadi index cuma use use aja nanti

2021-01-04 12:35 UTC, ivantjendra reviewed
Overall udah ok.

2021-01-04 14:30 UTC, ical10 commented on server/controllers/todosController.js
> +                    if (error.type === 'Validation error') {
yang ini pas saya coba error.name dia undefined kak, sepertinya karena saya pake customValidator

2021-01-05 08:47 UTC, ical10 commented on server/controllers/todosController.js
> +const {Todo} = require('../models')
siap kak, ini masalah formatting otomatis dari plugin yang saya pasang (semacam prettier gitu, tapi lupa gimana cara disable-nya), nanti saya liat lagi.

2021-01-05 08:51 UTC, ical10 reviewed
duplicate: cleaning up codes and implementing async-await in authentication using jwt.

2021-01-05 09:13 UTC, ivantjendra commented on server/routes/index.js
> +router.use(authRouter)
ini mending register login di sini langsung aja kalo gk ada prefix misal `/users` gitu. Kalau mau tetep pakai use mending di kasih `/users`. Biar enak bacanya

2021-01-05 09:13 UTC, ivantjendra commented on server/middlewares/auth.js
> +const {checkToken} = require('../helpers/jwt')
ini kalo destructure di kasih spasi ya
```js
const { checkToken } =
```

2021-01-05 09:13 UTC, ivantjendra commented on server/middlewares/auth.js
> +const {checkToken} = require('../helpers/jwt')
Yang lain nya juga

2021-01-05 09:13 UTC, ivantjendra commented on server/controllers/TodoController.js
> +                res.status(500).json({message: "Internal server error."})
ini sama kyak di `middlewares/auth.js`
```js
res.status(500).json({ message: 'Internal Server Error' })
```

2021-01-05 09:13 UTC, ivantjendra commented on server/controllers/TodoController.js
> +                    if (error.type === 'Validation error') {
ini if nya itu ke `name` nya aja. Kalau name nya `SequelizeValidationError` maka apa gitu

2021-01-05 09:13 UTC, ivantjendra commented on server/controllers/TodoController.js
> +                if (err.errors) {
ini juga di benerin

2021-01-05 09:15 UTC, ivantjendra requested changes
Dibenerin ya udah gw comment.

2021-01-08 13:30 UTC, merged